var hierarchy =
[
    [ "VieVS::AstrometricCalibratorBlock", "class_vie_v_s_1_1_astrometric_calibrator_block.html", null ],
    [ "VieVS::AstronomicalParameters", "class_vie_v_s_1_1_astronomical_parameters.html", null ],
    [ "SGP4::CommonConstants", "struct_s_g_p4_1_1_common_constants.html", null ],
    [ "VieVS::ParameterSettings::Contact", "struct_vie_v_s_1_1_parameter_settings_1_1_contact.html", null ],
    [ "CoordGeodetic", "struct_coord_geodetic.html", null ],
    [ "CoordTopocentric", "struct_coord_topocentric.html", null ],
    [ "DateTime", "class_date_time.html", null ],
    [ "SGP4::DeepSpaceConstants", "struct_s_g_p4_1_1_deep_space_constants.html", null ],
    [ "Eci", "class_eci.html", null ],
    [ "VieVS::Solver::EstimationParamEOP", "struct_vie_v_s_1_1_solver_1_1_estimation_param_e_o_p.html", null ],
    [ "VieVS::Solver::EstimationParamSource", "struct_vie_v_s_1_1_solver_1_1_estimation_param_source.html", null ],
    [ "VieVS::Solver::EstimationParamStation", "struct_vie_v_s_1_1_solver_1_1_estimation_param_station.html", null ],
    [ "VieVS::AbstractSource::Event", "struct_vie_v_s_1_1_abstract_source_1_1_event.html", null ],
    [ "VieVS::Baseline::Event", "struct_vie_v_s_1_1_baseline_1_1_event.html", null ],
    [ "VieVS::Station::Event", "struct_vie_v_s_1_1_station_1_1_event.html", null ],
    [ "VieVS::Flags", "class_vie_v_s_1_1_flags.html", null ],
    [ "VieVS::FocusCorners", "class_vie_v_s_1_1_focus_corners.html", null ],
    [ "focusCorners", "classfocus_corners.html", null ],
    [ "iauASTROM", "structiau_a_s_t_r_o_m.html", null ],
    [ "iauLDBODY", "structiau_l_d_b_o_d_y.html", null ],
    [ "SGP4::IntegratorParams", "struct_s_g_p4_1_1_integrator_params.html", null ],
    [ "VieVS::LogParser::LogScan", "struct_vie_v_s_1_1_log_parser_1_1_log_scan.html", null ],
    [ "VieVS::LookupTable", "class_vie_v_s_1_1_lookup_table.html", null ],
    [ "SGP4::NearSpaceConstants", "struct_s_g_p4_1_1_near_space_constants.html", null ],
    [ "Observer", "class_observer.html", null ],
    [ "VieVS::AbstractSource::Optimization", "struct_vie_v_s_1_1_abstract_source_1_1_optimization.html", null ],
    [ "OrbitalElements", "class_orbital_elements.html", null ],
    [ "VieVS::ParameterGroup", "class_vie_v_s_1_1_parameter_group.html", null ],
    [ "VieVS::MultiScheduling::Parameters", "struct_vie_v_s_1_1_multi_scheduling_1_1_parameters.html", null ],
    [ "VieVS::Initializer::Parameters", "struct_vie_v_s_1_1_initializer_1_1_parameters.html", null ],
    [ "VieVS::Scheduler::Parameters", "struct_vie_v_s_1_1_scheduler_1_1_parameters.html", null ],
    [ "VieVS::ParameterSettings::ParametersBaselines", "struct_vie_v_s_1_1_parameter_settings_1_1_parameters_baselines.html", null ],
    [ "VieVS::ParameterSettings", "class_vie_v_s_1_1_parameter_settings.html", null ],
    [ "VieVS::ParameterSetup", "class_vie_v_s_1_1_parameter_setup.html", null ],
    [ "VieVS::ParameterSettings::ParametersSources", "struct_vie_v_s_1_1_parameter_settings_1_1_parameters_sources.html", null ],
    [ "VieVS::ParameterSettings::ParametersStations", "struct_vie_v_s_1_1_parameter_settings_1_1_parameters_stations.html", null ],
    [ "VieVS::Solver::Partials", "struct_vie_v_s_1_1_solver_1_1_partials.html", null ],
    [ "VieVS::Initializer::PRECALC", "struct_vie_v_s_1_1_initializer_1_1_p_r_e_c_a_l_c.html", null ],
    [ "VieVS::Quasar::PreCalculated", "struct_vie_v_s_1_1_quasar_1_1_pre_calculated.html", null ],
    [ "VieVS::Scheduler::PreCalculated", "struct_vie_v_s_1_1_scheduler_1_1_pre_calculated.html", null ],
    [ "runtime_error", null, [
      [ "DecayedException", "class_decayed_exception.html", null ],
      [ "SatelliteException", "class_satellite_exception.html", null ],
      [ "TleException", "class_tle_exception.html", null ]
    ] ],
    [ "VieVS::Scan::ScanSequence", "struct_vie_v_s_1_1_scan_1_1_scan_sequence.html", null ],
    [ "SGP4", "class_s_g_p4.html", null ],
    [ "VieVS::Simulator::SimPara", "struct_vie_v_s_1_1_simulator_1_1_sim_para.html", null ],
    [ "SolarPosition", "class_solar_position.html", null ],
    [ "VieVS::Station::Statistics", "struct_vie_v_s_1_1_station_1_1_statistics.html", null ],
    [ "VieVS::Baseline::Statistics", "struct_vie_v_s_1_1_baseline_1_1_statistics.html", null ],
    [ "VieVS::AbstractSource::Statistics", "struct_vie_v_s_1_1_abstract_source_1_1_statistics.html", null ],
    [ "VieVS::Subnetting", "class_vie_v_s_1_1_subnetting.html", [
      [ "VieVS::Subnetting_minIdle", "class_vie_v_s_1_1_subnetting__min_idle.html", null ],
      [ "VieVS::Subnetting_percent", "class_vie_v_s_1_1_subnetting__percent.html", null ]
    ] ],
    [ "TimeSpan", "class_time_span.html", null ],
    [ "VieVS::TimeSystem", "class_vie_v_s_1_1_time_system.html", null ],
    [ "Tle", "class_tle.html", null ],
    [ "Vector", "struct_vector.html", null ],
    [ "VieVS::VieSchedpp", "class_vie_v_s_1_1_vie_schedpp.html", null ],
    [ "VieVS::VieVS_Object", "class_vie_v_s_1_1_vie_v_s___object.html", [
      [ "VieVS::AbstractAntenna", "class_vie_v_s_1_1_abstract_antenna.html", [
        [ "VieVS::Antenna_AzEl", "class_vie_v_s_1_1_antenna___az_el.html", null ],
        [ "VieVS::Antenna_GGAO", "class_vie_v_s_1_1_antenna___g_g_a_o.html", null ],
        [ "VieVS::Antenna_HaDc", "class_vie_v_s_1_1_antenna___ha_dc.html", null ],
        [ "VieVS::Antenna_XYew", "class_vie_v_s_1_1_antenna___x_yew.html", null ]
      ] ],
      [ "VieVS::AbstractCableWrap", "class_vie_v_s_1_1_abstract_cable_wrap.html", [
        [ "VieVS::CableWrap_AzEl", "class_vie_v_s_1_1_cable_wrap___az_el.html", null ],
        [ "VieVS::CableWrap_HaDc", "class_vie_v_s_1_1_cable_wrap___ha_dc.html", null ],
        [ "VieVS::CableWrap_XYew", "class_vie_v_s_1_1_cable_wrap___x_yew.html", null ]
      ] ],
      [ "VieVS::AbstractFlux", "class_vie_v_s_1_1_abstract_flux.html", [
        [ "VieVS::Flux_B", "class_vie_v_s_1_1_flux___b.html", null ],
        [ "VieVS::Flux_M", "class_vie_v_s_1_1_flux___m.html", null ]
      ] ],
      [ "VieVS::AbstractHorizonMask", "class_vie_v_s_1_1_abstract_horizon_mask.html", [
        [ "VieVS::HorizonMask_line", "class_vie_v_s_1_1_horizon_mask__line.html", null ],
        [ "VieVS::HorizonMask_step", "class_vie_v_s_1_1_horizon_mask__step.html", null ]
      ] ],
      [ "VieVS::Ast", "class_vie_v_s_1_1_ast.html", null ],
      [ "VieVS::CalibratorBlock", "class_vie_v_s_1_1_calibrator_block.html", null ],
      [ "VieVS::Equipment", "class_vie_v_s_1_1_equipment.html", [
        [ "VieVS::Equipment_elDependent", "class_vie_v_s_1_1_equipment__el_dependent.html", null ]
      ] ],
      [ "VieVS::Freq::Chan_def", "class_vie_v_s_1_1_freq_1_1_chan__def.html", null ],
      [ "VieVS::HighImpactScanDescriptor", "class_vie_v_s_1_1_high_impact_scan_descriptor.html", null ],
      [ "VieVS::HighImpactScanDescriptor::AzElDescriptor", "class_vie_v_s_1_1_high_impact_scan_descriptor_1_1_az_el_descriptor.html", null ],
      [ "VieVS::Initializer", "class_vie_v_s_1_1_initializer.html", null ],
      [ "VieVS::LogParser", "class_vie_v_s_1_1_log_parser.html", null ],
      [ "VieVS::MultiScheduling", "class_vie_v_s_1_1_multi_scheduling.html", null ],
      [ "VieVS::Network", "class_vie_v_s_1_1_network.html", null ],
      [ "VieVS::Observation", "class_vie_v_s_1_1_observation.html", null ],
      [ "VieVS::ObservingMode", "class_vie_v_s_1_1_observing_mode.html", null ],
      [ "VieVS::OperationNotes", "class_vie_v_s_1_1_operation_notes.html", null ],
      [ "VieVS::PointingVector", "class_vie_v_s_1_1_pointing_vector.html", null ],
      [ "VieVS::Position", "class_vie_v_s_1_1_position.html", null ],
      [ "VieVS::Scan", "class_vie_v_s_1_1_scan.html", null ],
      [ "VieVS::ScanTimes", "class_vie_v_s_1_1_scan_times.html", null ],
      [ "VieVS::Skd", "class_vie_v_s_1_1_skd.html", null ],
      [ "VieVS::SkdCatalogReader", "class_vie_v_s_1_1_skd_catalog_reader.html", null ],
      [ "VieVS::SkdParser", "class_vie_v_s_1_1_skd_parser.html", null ],
      [ "VieVS::SkyCoverage", "class_vie_v_s_1_1_sky_coverage.html", null ],
      [ "VieVS::SNR_table", "class_vie_v_s_1_1_s_n_r__table.html", null ],
      [ "VieVS::Solver::PWL", "class_vie_v_s_1_1_solver_1_1_p_w_l.html", null ],
      [ "VieVS::SourceList", "class_vie_v_s_1_1_source_list.html", null ],
      [ "VieVS::SourceStatistics", "class_vie_v_s_1_1_source_statistics.html", null ],
      [ "VieVS::StationEndposition", "class_vie_v_s_1_1_station_endposition.html", null ],
      [ "VieVS::Subcon", "class_vie_v_s_1_1_subcon.html", null ],
      [ "VieVS::Track::Fanout_definition", "class_vie_v_s_1_1_track_1_1_fanout__definition.html", null ],
      [ "VieVS::Unknown", "class_vie_v_s_1_1_unknown.html", null ],
      [ "VieVS::Vex", "class_vie_v_s_1_1_vex.html", null ],
      [ "VieVS::VieVS_NamedObject", "class_vie_v_s_1_1_vie_v_s___named_object.html", [
        [ "VieVS::AbstractSource", "class_vie_v_s_1_1_abstract_source.html", [
          [ "VieVS::Quasar", "class_vie_v_s_1_1_quasar.html", null ],
          [ "VieVS::Satellite", "class_vie_v_s_1_1_satellite.html", null ]
        ] ],
        [ "VieVS::AbstractSource::Parameters", "class_vie_v_s_1_1_abstract_source_1_1_parameters.html", null ],
        [ "VieVS::Baseline", "class_vie_v_s_1_1_baseline.html", null ],
        [ "VieVS::Baseline::Parameters", "class_vie_v_s_1_1_baseline_1_1_parameters.html", null ],
        [ "VieVS::Bbc", "class_vie_v_s_1_1_bbc.html", null ],
        [ "VieVS::Bbc::Bbc_assign", "class_vie_v_s_1_1_bbc_1_1_bbc__assign.html", null ],
        [ "VieVS::Freq", "class_vie_v_s_1_1_freq.html", null ],
        [ "VieVS::If", "class_vie_v_s_1_1_if.html", null ],
        [ "VieVS::If::If_def", "class_vie_v_s_1_1_if_1_1_if__def.html", null ],
        [ "VieVS::Mode", "class_vie_v_s_1_1_mode.html", null ],
        [ "VieVS::Output", "class_vie_v_s_1_1_output.html", null ],
        [ "VieVS::Scheduler", "class_vie_v_s_1_1_scheduler.html", null ],
        [ "VieVS::Simulator", "class_vie_v_s_1_1_simulator.html", null ],
        [ "VieVS::Solver", "class_vie_v_s_1_1_solver.html", null ],
        [ "VieVS::Station", "class_vie_v_s_1_1_station.html", null ],
        [ "VieVS::Station::Parameters", "class_vie_v_s_1_1_station_1_1_parameters.html", null ],
        [ "VieVS::Track", "class_vie_v_s_1_1_track.html", null ]
      ] ]
    ] ],
    [ "VieVS::WeightFactors", "class_vie_v_s_1_1_weight_factors.html", null ]
];